### ISSUE TITLE
num_features - double-double (4x) intentional?

### ISSUE THREAD

**Issue by cboulay** [magland/ml_ms4alg#26]
`run_sort` extracts `num_features` from the opts dict. So we'll take this to be the user-specified number of features.

In `run_sort` line 409, we have `compute_event_features_from_timeseries_model(..., num_features=num_features*2, ...)`
There's no comment as to why it's doubled here so I won't speculate.

`num_features` is not used in `compute_event_features_from_timeseries_model`, until:
```Python
# use twice as many features, because of branch method
principal_components = compute_principal_components(..., num_features*2)
```
So `num_features`, which was already doubled, is doubled again.

1. Is the double-doubling intentional?
2. In `run_sort`,  `branch_cluster(features, branch_depth=2, npca=num_features)`. If branch_depth weren't hard-coded at 2 and was instead a user-defined integer `B`, should the multiplier on the number of features be `B`, or `2**(B - current_branch_lvl)`?

**Comment by magland** [comment]
Hi @cboulay. I think this was not intentional. Hmmm. I think the number of features going in to compute_event_features_from_timeseries_model should not be doubled. However, I'm not sure what to do at this point since a lot of people have been using the code as is, so I don't want to change it without some sort of mechanism to notify users of the change. Hmmmm....

**Comment by magland** [comment]
Actually I think that fortunately, ultimately, num_features is being used (not num_features*2) as explained in my response to https://github.com/magland/ml_ms4alg/issues/27

But there's still the question of why the *2 is needed at that point in the code.

**Comment by cboulay** [comment]
OK. So you're returning 4x num_features components from the time series models, but then only using `num_features` on the branched clustering. I doubt the extra *2 will make any difference. Unless your users are purposely living on the lower edge of num_features, I suspect that going from 2x to 4x features in the first PCA will only make a difference in variance-accounted-for on the order of 0.1%, so removing the extra 2* will have no practical effect. Mind you, I'm a bad source for this because I'm not using high density grids.

But now that I understand this a little better, I'd like to reformulate my question 2 a bit better:

When doing branched clustering, is there any benefit to having the first branch operate on N features and the next branch operate on N//2 features? In other words, should the dimensionality of the feature subspace be halved with every branch?

**Comment by magland** [comment]
There are a couple different reasons for using PCA dimension reduction. The primary reason (in my mind) is to improve computational efficiency. The secondary reason has to do with removing some artifacts and problems caused by near-overlapping spikes. But I think that generally speaking, the higher the number of features, the more accurate things will be. So I would guess that your scheme would not really help (except perhaps with efficiently, very modestly though)

**Comment by cboulay** [comment]
Got it, thanks. I was just trying to interpret that code comment `# use twice as many features, because of branch method`. Even though I dont understand this code comment, I now have a much firmer grasp of how the ms4 alg works so I think I can proceed.

Thank you very much for your help!
